import type { CaseBehaviorContract } from "../types/scenario.js";

export const case01BehaviorContract: CaseBehaviorContract = {
  permittedFacts: ["Amara Johnson", "severe toothache", "jaw/facial swelling", "four-day onset", "pain approximately 8/10", "feverish", "breathing or swallowing difficulty", "type 2 diabetes", "hypertension", "metformin", "lisinopril", "no opioid or narcotic use or misuse history", "no known medication allergies"],
  firstResponseFactLimit: 4,
  stableFacts: [
    { id: "duration", label: "four-day symptom duration", acceptedPatterns: [/four days?/i, /4 days?/i], contradictionPatterns: [/\b(?:pain|ache|swelling|symptoms?|it)\b.{0,30}\b(?:started|began|for|since)\b.{0,15}\b(?:yesterday|weeks?|months?|years?)\b/i] },
    { id: "severity", label: "pain around 8/10", acceptedPatterns: [/\b8\s*(?:\/|out of)\s*10\b/i, /\bsevere\b/i], contradictionPatterns: [/\b(?:[0-4])\s*(?:\/|out of)\s*10\b/i, /\bmild pain\b/i] },
    { id: "swelling", label: "jaw or facial swelling", acceptedPatterns: [/\bswoll(?:en|ing)\b/i], contradictionPatterns: [/\b(?:no|not|haven't had|have not had)\b.{0,25}\bswoll(?:en|ing)\b/i] },
    { id: "medical-history", label: "type 2 diabetes and hypertension", acceptedPatterns: [/\bdiabetes\b/i, /\bhypertension\b/i], contradictionPatterns: [/\b(?:no|don't have|do not have)\b.{0,35}\b(?:diabetes|hypertension|medical conditions?)\b/i] },
    { id: "allergies", label: "no known medication allergies", acceptedPatterns: [/\bno known (?:medication )?allerg/i, /\bnot allergic\b/i, /\b(?:don't|do not) have (?:any )?(?:known )?(?:drug|medication)?\s*allerg/i], contradictionPatterns: [/\b(?:i am|i'm)\s+(?!not\b)allergic to\s+(?:penicillin|amoxicillin|ibuprofen|aspirin)\b/i] },
    { id: "opioid-history", label: "no opioid use or misuse history", acceptedPatterns: [/\b(?:no|not|never|haven't|have not|don't|do not)\b.{0,55}\b(?:opioids?|opiates?|narcotics?|prescription (?:painkillers?|pain (?:medication|medicine|pills?))|misus(?:e|ed)|abus(?:e|ed)|dependen(?:ce|t)|addict(?:ion|ed))\b/i, /\bnor\b.{0,55}\b(?:misus(?:e|ed)|abus(?:e|ed)|dependen(?:ce|t)|addict(?:ion|ed))\b/i], contradictionPatterns: [/\byes\b.{0,55}\b(?:opioids?|opiates?|narcotics?|misus(?:e|ed)|dependen(?:ce|t))\b/i, /(?<!nor have )\bi(?:'ve| have| had)\s+(?!not\b|never\b|no\b).{0,45}\b(?:opioids?|opiates?|narcotics?|prescription (?:painkillers?|pain (?:medication|medicine|pills?))|misus(?:e|ed)|dependen(?:ce|t))\b/i, /\bi\s+(?:used|took|misused|abused)\b.{0,35}\b(?:opioids?|opiates?|narcotics?|prescription (?:painkillers?|pain (?:medication|medicine|pills?)))\b/i, /\bi\s+(?:was|am)\s+(?:dependent|addicted)\b.{0,25}\bopioids?\b/i], directQuestionPatterns: [/\b(?:opioids?|opiates?|narcotics?|prescription (?:painkillers?|pain (?:medication|medicine|pills?))|opioid (?:use|misuse|abuse|dependence|addiction))\b/i] },
  ],
};

export const case02BehaviorContract: CaseBehaviorContract = {
  permittedFacts: ["Marcus Lee", "severe upper-right tooth pain", "symptoms have worsened over seven days", "feverish", "weak and generally sick", "increasing right-cheek swelling over about 24 hours", "no drooling, voice change, breathing difficulty, or inability to swallow liquids", "mouth opening is possible but uncomfortable", "ibuprofen 400 mg as needed about every six hours", "no opioid-use or misuse history", "no known drug allergies", "half-pack-per-day smoking", "rare alcohol use", "no illicit-drug use"],
  firstResponseFactLimit: 4,
  stableFacts: [
    { id: "location", label: "upper-right tooth location", acceptedPatterns: [/upper[- ]right/i], contradictionPatterns: [/\b(?:upper[- ]left|lower[- ]right|lower[- ]left|left side)\b/i] },
    {
      id: "duration",
      label: "approximately seven-day symptom duration",
      canonicalDurationDays: 7,
      acceptedPatterns: [
        /\b(?:seven|7)\s+days?\b/i,
        /\b(?:(?:about|approximately|around|roughly|nearly)\s+)?(?:a|one)\s+week\b/i,
      ],
      contradictionPatterns: [
        /\b(?:started|began|lasted|going on|hurting|worsening|getting worse)\b.{0,30}\b(?:today|yesterday|(?:one|two|three|four|five|six|1|2|3|4|5|6|couple of|few)\s+days?|(?:two|three|four|2|3|4)\s+weeks?|months?|years?)\b/i,
        /\b(?:pain|ache|symptoms?)\b.{0,30}\bfor\b.{0,20}\b(?:one|two|three|four|five|six|1|2|3|4|5|6|couple of|few)\s+days?\b/i,
      ],
    },
    { id: "airway", label: "no breathing or swallowing difficulty", acceptedPatterns: [/\bno\b.{0,45}\b(?:breath|swallow)/i, /haven't had\b.{0,45}\b(?:breath|swallow)/i, /\b(?:can|able to)\b.{0,20}\bbreath(?:e|ing)?\b.{0,20}\b(?:normally|fine|okay|without (?:trouble|difficulty))/i], contradictionPatterns: [/\bi(?:'m| am)\s+(?!not\b)(?:having\s+)?(?:trouble|difficulty|a hard time)\b.{0,20}\b(?:breath|swallow)/i, /\bi(?: have|'ve)\s+(?!no\b|not\b)(?:trouble|difficulty|a hard time)\b.{0,20}\b(?:breath|swallow)/i] },
    { id: "swelling", label: "increasing right-cheek swelling", acceptedPatterns: [/\bright\b.{0,25}\b(?:cheek|face)\b.{0,25}\b(?:swollen|swelling)\b/i, /\b(?:swollen|swelling)\b.{0,25}\bright\b.{0,20}\b(?:cheek|face|side)\b/i, /\bright cheek\b.{0,30}\b(?:more swollen|getting (?:more )?swollen|increas(?:e|ed|ing))/i], contradictionPatterns: [/\b(?:no|not|haven't|have not)\b.{0,25}\b(?:swollen|swelling)\b/i, /\b(?:left|lower[- ]left)\b.{0,25}\b(?:cheek|face|facial)\b.{0,20}\b(?:swollen|swelling)\b/i, /\b(?:swollen|swelling)\b.{0,25}\b(?:left|lower[- ]left)\b/i, /\bswelling\b.{0,20}\b(?:resolved|gone|went away|improved)\b/i] },
  ],
};

export const case03BehaviorContract: CaseBehaviorContract = {
  permittedFacts: ["Elena Garcia", "25-year-old patient", "right mandibular posterior tooth pain", "three-day progression", "constant throbbing 8/10 pain", "pain radiating toward the right ear", "pain with biting, chewing, and tapping", "no current cold pain", "mild lower-right facial puffiness", "localized gum swelling", "no fever or airway symptoms", "stomach ulcers", "Pepcid as needed", "ibuprofen stomach intolerance but not allergy", "no known drug or penicillin allergies", "no prior opioid use or misuse", "non-smoker", "occasional alcohol", "no illicit drugs", "extensive nonspecific dental work", "crown with uncertain root-canal history", "dentist appointment next week"],
  firstResponseFactLimit: 4,
  stableFacts: [
    { id: "location", label: "right mandibular posterior location", canonicalLocation: "lower-right", acceptedPatterns: [/\b(?:lower[- ]right|right (?:mandibular|lower))\b/i], contradictionPatterns: [/\b(?:left|upper[- ]right|maxillary)\b.{0,25}\b(?:tooth|molar|jaw)\b/i], directQuestionPatterns: [/\bwhere|which tooth|what side|upper or lower\b/i] },
    { id: "duration", label: "three-day symptom duration", canonicalDurationDays: 3, acceptedPatterns: [/\b(?:three|3)\s+days?\b/i], contradictionPatterns: [/\b(?:started|began|hurting|worsening|going on)\b.{0,30}\b(?:(?:one|two|four|five|six|seven|1|2|4|5|6|7)\s+days?|(?:one|two|three|1|2|3)\s+weeks?|months?|years?)\b/i], directQuestionPatterns: [/\bhow long|when.{0,20}(?:start|begin)|duration\b/i] },
    { id: "severity", label: "8/10 severe pain", acceptedPatterns: [/\b8\s*(?:\/|out of|on (?:a )?(?:pain )?scale of(?: 1 to)?)\s*10\b/i, /\beight (?:out of|on (?:a )?(?:pain )?scale of(?: one to)?) ten\b/i, /^\s*(?:eight|8)[.!]?\s*$/i], contradictionPatterns: [/\b(?:[0-7]|9|10)\s*(?:\/|out of|on (?:a )?(?:pain )?scale of(?: 1 to)?)\s*10\b/i], directQuestionPatterns: [/\bhow bad|severity|pain scale|out of ten\b/i] },
    { id: "swelling", label: "mild lower-right facial puffiness", acceptedPatterns: [/\b(?:puffy|swoll(?:en|ing))\b/i], contradictionPatterns: [/\b(?:no|not|haven't|have not)\b.{0,25}\b(?:puffy|swoll(?:en|ing))\b/i], directQuestionPatterns: [/\bswell|puffy\b/i] },
    { id: "fever", label: "no fever", acceptedPatterns: [/\b(?:no|not|haven't|have not|don't have|do not have)\b.{0,55}\bfever/i], contradictionPatterns: [/\bi(?:'ve| have| am|'m)\b(?!\s+(?:not|never)\b).{0,20}\bfever(?:ish)?\b/i, /\bi did have\b.{0,20}\bfever(?:ish)?\b/i, /\bfeeling\b.{0,20}\bfever(?:ish)?\b/i], directQuestionPatterns: [/\bfever|temperature|chills\b/i] },
    { id: "ulcers", label: "stomach-ulcer history", acceptedPatterns: [/\bstomach ulcers?\b/i], contradictionPatterns: [/\b(?:no|don't have|do not have)\b.{0,20}\bulcers?\b/i], directQuestionPatterns: [/\bmedical history|conditions|ulcers\b/i] },
    { id: "ibuprofen", label: "poor ibuprofen tolerance", acceptedPatterns: [/\b(?:ibuprofen|advil|motrin)\b.{0,35}\b(?:upsets?|bothers?|poorly tolerate|stomach|avoid)\b/i], contradictionPatterns: [/\b(?:ibuprofen|advil|motrin)\b.{0,25}\b(?:works well|no problem|tolerate well)\b/i], directQuestionPatterns: [/\bibuprofen|advil|motrin\b/i] },
    { id: "allergies", label: "no known drug allergies", acceptedPatterns: [/\bno known (?:drug|medication)?\s*allerg/i, /\b(?:don't|do not) have (?:any )?(?:known )?(?:drug )?allerg/i, /\bnot allergic\b/i], contradictionPatterns: [/\b(?:i am|i'm)\s+(?!not\b)allergic to\b.{0,20}\b(?:penicillin|amoxicillin|ibuprofen)\b/i], directQuestionPatterns: [/\ballerg/i] },
    { id: "radiation", label: "right-ear radiation", acceptedPatterns: [/\bright ear\b/i], contradictionPatterns: [/\bleft ear\b/i], directQuestionPatterns: [/\btravel|radiat|go anywhere|ear\b/i] },
    { id: "cold", label: "no current cold pain", acceptedPatterns: [/\b(?:cold|cold drinks?)\b.{0,35}\b(?:doesn't|does not|not|no)\b.{0,20}\b(?:hurt|pain)/i, /\b(?:no|not|doesn't|does not)\b.{0,35}\b(?:hurt|pain)\b.{0,25}\bcold\b/i], contradictionPatterns: [/\bcold\b.{0,25}\b(?:hurts?|painful|worse|lingers?)\b/i], directQuestionPatterns: [/\bcold|thermal\b/i] },
    { id: "root-canal", label: "uncertain root-canal history", acceptedPatterns: [/\b(?:not sure|unsure|don't know|do not know|don't remember)\b.{0,55}\broot canal\b/i], contradictionPatterns: [/\b(?:definitely|yes|no|never|already)\b.{0,35}\broot canal\b/i], directQuestionPatterns: [/\broot canal|nerve removed\b/i] },
    { id: "opioid-history", label: "no opioid-use or misuse history", acceptedPatterns: [/\b(?:no|never|haven't|have not)\b.{0,55}\b(?:opioids?|narcotics?|misuse|abuse)\b/i], contradictionPatterns: [/\b(?:yes|have|had|used|took)\b.{0,30}\b(?:opioids?|narcotics?)\b/i], directQuestionPatterns: [/\bopioid|narcotic|opiate\b/i] },
  ],
};

export const case04BehaviorContract: CaseBehaviorContract = {
  permittedFacts: ["Noah Patel", "38-year-old patient", "lower-left molar pain", "five-day returned-pain progression", "prior severe episode about a week ago stopped then returned", "sharp biting pain intensified over 48 hours", "constant 7/10 pain", "sharp biting, chewing, and tapping pain", "historical but not current cold pain", "large filling placed about 20 years ago with suspected but unconfirmed break", "no swelling, drainage, fever, or airway symptoms", "penicillin allergy causing hives only", "ibuprofen 400 mg as needed without adequate relief and no contraindication", "no prior opioid use or misuse", "otherwise healthy", "one-pack-per-day smoker", "occasional alcohol", "no illicit drugs", "last dental visit five years ago", "no dental insurance or current dentist access", "wants to save the tooth"],
  firstResponseFactLimit: 4,
  stableFacts: [
    { id: "location", label: "left mandibular first-molar location", canonicalLocation: "lower-left", acceptedPatterns: [/\b(?:lower[- ]left|left (?:mandibular|lower))\b/i], contradictionPatterns: [/\b(?:right|upper[- ]left|maxillary)\b.{0,25}\b(?:tooth|molar|jaw)\b/i], directQuestionPatterns: [/\bwhere|which tooth|what side|upper or lower\b/i] },
    { id: "duration", label: "five-day returned-pain duration", canonicalDurationDays: 5, acceptedPatterns: [/\b(?:five|5)\s+days?\b/i], contradictionPatterns: [/\b(?:returned|worsening|going on|hurting)\b.{0,30}\b(?:(?:one|two|three|four|six|seven|1|2|3|4|6|7)\s+days?|(?:one|two|three|1|2|3)\s+weeks?|months?|years?)\b/i], directQuestionPatterns: [/\bhow long|duration\b/i] },
    { id: "severity", label: "7/10 pain", acceptedPatterns: [/\b7\s*(?:\/|out of|on (?:a )?(?:pain |numeric )?scale of(?: 1 to)?)\s*10\b/i, /\b7 on a ten(?:[- ]point)? (?:pain |numeric )?scale\b/i, /\bseven (?:out of|on (?:a )?scale of(?: one to)?) ten\b/i, /\bseven on a ten(?:[- ]point)? scale\b/i, /^\s*(?:seven|7)[.!]?\s*$/i], contradictionPatterns: [/\b(?:[0-6]|8|9|10)\s*(?:\/|out of|on (?:a )?(?:pain |numeric )?scale of(?: 1 to)?)\s*10\b/i, /\b(?:[0-6]|8|9|10) on a ten(?:[- ]point)? (?:pain |numeric )?scale\b/i, /\b(?:zero|one|two|three|four|five|six|eight|nine|ten) (?:out of ten|on a ten(?:[- ]point)? scale)\b/i], directQuestionPatterns: [/\bhow bad|severity|pain scale|out of ten\b/i] },
    { id: "swelling", label: "no swelling", acceptedPatterns: [/\b(?:no|not|haven't|have not|don't have|do not have)\b.{0,45}\bswell/i], contradictionPatterns: [/\b(?:my|the)\b.{0,20}\bswoll(?:en|ing)\b/i], directQuestionPatterns: [/\bswell/i] },
    { id: "fever", label: "no fever or chills", acceptedPatterns: [/\b(?:no|not|haven't|have not|don't have|do not have)\b.{0,55}\b(?:fever|chills)/i], contradictionPatterns: [/\bi(?:'ve| have| am|'m)\b(?!\s+(?:no|not|never)\b).{0,20}\b(?:fever(?:ish)?|chills)\b/i, /\bi did have\b.{0,20}\b(?:fever|chills)\b/i, /\bfeeling\b.{0,20}\b(?:feverish|chills)\b/i], directQuestionPatterns: [/\bfever|chills\b/i] },
    { id: "penicillin", label: "penicillin allergy with hives", acceptedPatterns: [/\bpenicillin\b.{0,30}\b(?:allerg(?:ic|y|ies)?|hives)\b/i, /\b(?:allerg(?:ic|y|ies)?|hives)\b.{0,30}\bpenicillin\b/i], contradictionPatterns: [/\bnot allergic to penicillin\b/i, /\bno\b(?!\s+other\b).{0,25}\ballerg(?:y|ies)\b/i, /\bpenicillin\b.{0,30}\b(?:anaphylaxis|angioedema|stomach upset)\b/i], directQuestionPatterns: [/\bpenicillin|allerg|reaction\b/i] },
    { id: "sequence", label: "week-old episode stopped and returned with 48-hour intensification", acceptedPatterns: [/\b(?:week|seven days)\b.{0,55}\bstopped\b.{0,55}\b(?:returned|came back|hurting again)\b/i, /\b(?:48|forty[- ]eight)\s+hours?\b.{0,45}\b(?:sharp|intensified|worse)\b/i, /\b(?:sharp(?:er)?|intensified|worse)\b.{0,45}\b(?:48|forty[- ]eight)\s+hours?\b/i], contradictionPatterns: [/\b(?:continuous|without stopping)\b.{0,35}\b(?:week|seven days)\b/i, /\b(?:started|began)\b.{0,30}\b(?:48|forty[- ]eight)\s+hours? ago\b/i], directQuestionPatterns: [/\bweek ago|stop|return|come back|48 hours|two days|intensif/i] },
    { id: "filling", label: "20-year-old filling with unconfirmed break", acceptedPatterns: [/\b(?:twenty|20)\s+years?\b.{0,45}\bfilling\b|\bfilling\b.{0,45}\b(?:twenty|20)\s+years?\b/i, /\b(?:think|may|might)\b.{0,35}\bfilling\b.{0,25}\b(?:broke|broken|failed)\b/i], contradictionPatterns: [/\b(?:definitely|certainly)\b.{0,35}\bfilling\b.{0,25}\b(?:broke|broken|failed)\b|\bfilling\b.{0,35}\b(?:definitely|certainly)\b.{0,25}\b(?:broke|broken|failed)\b/i], directQuestionPatterns: [/\bfilling|restoration\b/i] },
    { id: "cold-current", label: "no current cold sensitivity", acceptedPatterns: [/\bcold\b.{0,80}\b(?:doesn't|does not|no longer|not (?:now|anymore)|is not painful now)\b/i, /\b(?:doesn't|does not|no longer|don't feel anything)\b.{0,80}\bcold\b/i], contradictionPatterns: [/\b(?:now|currently)\b.{0,20}\bcold\b.{0,20}\b(?:hurts?|painful|worse)\b/i, /\bcold\b.{0,20}\b(?:still|currently)\b.{0,15}\b(?:hurts?|painful|worse)\b/i], directQuestionPatterns: [/\bcold.{0,20}(?:still|now|current)/i] },
  ],
};

export const case05BehaviorContract: CaseBehaviorContract = {
  permittedFacts: ["Sofia Williams", "32-year-old patient", "lower-left jaw pain with exact tooth unknown to patient", "examination shows a large cavity on the lower-left first molar", "four-day progression", "constant deep throbbing 9/10 pain", "spontaneous and nocturnal pain", "cold worsens and pain lingers qualitatively", "chewing and slight biting discomfort", "no swelling, drainage, fever, or airway symptoms", "ibuprofen 400 mg without adequate relief", "no opioid-use or misuse history", "no known drug allergies or penicillin allergy", "otherwise healthy", "half-pack-per-day smoker", "occasional alcohol and no illicit drugs", "upper tooth extracted five years ago", "uninsured affordability barrier", "wants to save the tooth"],
  firstResponseFactLimit: 4,
  stableFacts: [
    { id: "location", label: "lower-left tooth location", acceptedPatterns: [/\b(?:lower[- ]left|bottom[- ]left|left (?:mandibular|lower))\b/i, /\bleft side\b.{0,25}\b(?:bottom|lower jaw|down low)\b/i, /\blower part\b.{0,20}\bleft side\b/i], contradictionPatterns: [/\b(?:pain|hurts?|painful tooth)\b.{0,30}\b(?:upper(?:[- ](?:left|right))?|maxillary)\b/i, /\b(?:upper(?:[- ](?:left|right))?|maxillary)\b.{0,30}\b(?:pain|hurts?|painful tooth)\b/i, /^\s*(?:it(?:'s| is)|the pain is)\s+(?:on|in)\s+(?:the\s+)?(?:upper[- ]left|upper[- ]right|lower[- ]right|right side|upper jaw)\b/i], directQuestionPatterns: [/\bwhere|which tooth|what side|upper or lower\b/i] },
    { id: "exact-tooth", label: "patient cannot identify exact tooth", acceptedPatterns: [/\b(?:can't|cannot|don't|do not)\b.{0,25}\b(?:tell|know|identify)\b.{0,30}\b(?:which|exact) tooth\b/i], contradictionPatterns: [/\b(?:know|definitely|exactly)\b.{0,30}\b(?:first molar|tooth number)\b|\b(?:first molar|tooth number)\b.{0,30}\b(?:know|definitely|exactly)\b/i], directQuestionPatterns: [/\bwhich (?:exact )?tooth|tooth number|first molar\b/i] },
    { id: "duration", label: "four-day symptom duration", canonicalDurationDays: 4, acceptedPatterns: [/\b(?:four|4)\s+days?\b/i], contradictionPatterns: [/\b(?:started|began|hurting|worsening|going on)\b.{0,30}\b(?:(?:one|two|three|five|six|seven|1|2|3|5|6|7)\s+days?|(?:one|two|three|1|2|3)\s+weeks?|months?|years?)\b/i], directQuestionPatterns: [/\bhow long|when.{0,20}(?:start|begin)|duration\b/i] },
    { id: "severity", label: "9/10 severe pain", acceptedPatterns: [/\b9\s*(?:\/|out of)\s*10\b/i, /\bnine out of ten\b/i, /\b(?:it(?:'s| is)|about|around)\s+(?:a\s+)?nine\b/i, /\bnine on (?:a )?(?:ten(?:[- ]point)? (?:pain )?scale|(?:pain )?scale of (?:10|ten))\b/i, /^\s*(?:nine|9)[.!]?\s*$/i], contradictionPatterns: [/\b(?:[0-8]|10)\s*(?:\/|out of)\s*10\b/i], directQuestionPatterns: [/\bhow bad|severity|pain scale|out of ten\b/i] },
    { id: "cold", label: "cold-worsened lingering pain", acceptedPatterns: [/\bcold\b.{0,90}\b(?:worse|hurts?|pain)\b.{0,90}\b(?:linger(?:s|ed|ing)?|doesn't stop|does not stop|didn't go away|did not go away|stay(?:s|ed)?|keeps? hurting)\b/i, /\b(?:pain\b.{0,25})?(?:linger(?:s|ed|ing)?|doesn't stop|does not stop|didn't go away|did not go away|stay(?:s|ed)?|keeps? hurting)\b.{0,90}\bcold\b/i, /\b(?:pain|it)\b.{0,80}\bafter\b.{0,50}\bcold\b/i], contradictionPatterns: [/\bcold\b.{0,25}\b(?:relieves?|helps?|calms?|stops immediately)\b/i], directQuestionPatterns: [/\bcold|thermal|stop immediately|linger\b/i] },
    { id: "swelling", label: "no swelling", acceptedPatterns: [/\b(?:no|not|haven't|have not|don't have|do not have)\b.{0,45}\bswell/i], contradictionPatterns: [/\b(?:my|the)\b.{0,20}\bswoll(?:en|ing)\b/i], directQuestionPatterns: [/\bswell/i] },
    { id: "fever", label: "no fever", acceptedPatterns: [/\b(?:no|not|haven't|have not|don't have|do not have)\b.{0,55}\bfever/i], contradictionPatterns: [/\b(?:i(?:'ve| have| am|'m)|feeling)\b.{0,20}\bfever(?:ish)?\b/i], directQuestionPatterns: [/\bfever|temperature|chills\b/i] },
    { id: "allergies", label: "no known drug allergies", acceptedPatterns: [/\bno known (?:drug|medication)?\s*allerg/i, /\b(?:don't|do not) have (?:any )?(?:known )?(?:drug )?allerg/i, /\bnot allergic\b/i], contradictionPatterns: [/\b(?:i am|i'm)\s+(?!not\b)allergic to\b.{0,20}\b(?:penicillin|amoxicillin|ibuprofen)\b/i], directQuestionPatterns: [/\ballerg/i] },
    { id: "smoking", label: "half-pack-per-day smoking history", acceptedPatterns: [/\b(?:smoke|smoking)\b.{0,35}\b(?:half|0\.5|one[- ]half)\b.{0,20}\bpack\b/i, /\bhalf[- ]?(?:a )?pack\b.{0,30}\b(?:smoke|cigarette)/i], contradictionPatterns: [/\b(?:don't|do not|never|not)\b.{0,20}\bsmok/i, /\bnon[- ]?smoker\b/i], directQuestionPatterns: [/\bsmok|tobacco|cigarette\b/i] },
    { id: "opioid-history", label: "no opioid-use or misuse history", acceptedPatterns: [/\b(?:no|never|haven't|have not)\b.{0,55}\b(?:opioids?|narcotics?|misuse|abuse)\b/i], contradictionPatterns: [/\b(?:yes|have|had|used|took)\b.{0,30}\b(?:opioids?|narcotics?)\b/i], directQuestionPatterns: [/\bopioid|narcotic|opiate\b/i] },
  ],
};
